[build]
  publish = "dist/ui-ux-portfolio"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Form notifications
[[plugins]]
  package = "@netlify/plugin-form-submissions"

[plugins.inputs]
  emailNotifications = true
  emailAddress = "hermionegomez49@gmail.com"
